name: Docker CI/CD - BCReddy
on:
  push:
    branches: [ "main" ]
jobs:
  dokcer_build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: chinnareddaiah/wsapp:0.1

      - name: Run Docker container on remote host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_DOCKER_HOST }}
          username: ${{ secrets.DEV_DOCKER_USER }}
          key: ${{ secrets.DEV_DOCKER_KEY }}
          script: |
            docker rm -f wsapp 2> /dev/null || true
            docker pull chinnareddaiah/wsapp:0.1
            docker run -d --name wsapp -p 8080:8080 chinnareddaiah/wsapp:0.1
